### PR TITLE
Update gulp.md documentation

### PR DESCRIPTION
**Pull request by paulpopus**
Update the gulp documentation to mention node_module resolution

### CODE REVIEW

**Comment by christiantjl** [comment]
TY for this, I had no idea the `--js` flag would accept a `package.json` until I saw your thread.

**Comment by ChadKillingsworth** [comment]
This really is not specific to gulp. Do you have a suggestion of where this should go? Perhaps on the main compiler documentation? We can definitely link to it from the gulp docs.

**Comment by paulpopus** [comment]
The main place in the documentation can also work. Just so generally people can find it, at least from googling it if nothing else.

**Comment by paulpopus** [comment]
@ChadKillingsworth I've got some time so I can move my changes to another documentation file, do you have a specific one in mind?

The example specifically is for Gulp though, so I'll split that.

**Comment by mprobst** [comment]
Internal issue b/171955360 created.

**Comment by ChadKillingsworth** [comment]
The [main compiler wiki pages](https://github.com/google/closure-compiler/wiki/JS-Modules) have now been updated with this information.

**Pull request closed without merging**
