### PR TITLE
Remove unnecessary whitespace

### PR DESCRIPTION
**Pull request by alubbe**
Just came across this inconsistency, thought it might be worth fixing.

### CODE REVIEW

**Comment by alubbe** [comment]
I signed it!

**Comment by MatrixFrog** [comment]
I think these are all already complying with the style that we typically use: Two space indent after a `{`, four when you need to indent mid-statement.

**Comment by alubbe** [comment]
Fair enough, had not heard of that style before.

**Comment by ChadKillingsworth** [comment]
It's on my list of todos to add ESLINT with the Google rule set.

**Pull request closed without merging**
