### PR TITLE
Update graal version to 20.2.0

### PR DESCRIPTION
**Pull request by ChadKillingsworth**
Update to the latest Graal release: https://www.graalvm.org/release-notes/20_2/#2020

### CODE REVIEW

**Comment by ChadKillingsworth** [comment]
Well I had hoped that the images were somehow back to the appropriate size, but still probably worthwhile to upgrade.

**Comment by ChadKillingsworth** [comment]
I tried downgrading GRAAL for linux and macos to see if smaller images returned, but it turned out to be a lot more work than I anticipated.

**Review by lauraharker — APPROVED** [review]

**Comment by mprobst** [comment]
Internal issue b/171955063 created.

**Comment by mprobst** [comment]
Is this ready to land?

**Pull request merged**
